# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    my_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider
    user_service.class: AppBundle\Core\Service\UserService
    user_dao.class: AppBundle\Core\Dao\UserDAO
    social_profile_util.class: AppBundle\Util\SocialProfileUtil

services:
  
    user_dao:
        class: "%user_dao.class%"
        arguments: ["@doctrine.orm.entity_manager","@logger"]
    
    user_service:
        class: "%user_service.class%"
        arguments: ["@user_dao","@logger"]
        
    my_user_provider:
        class: "%my_user_provider.class%"
        #this is the place where the properties are passed to the UserProvider - see config.yml
        arguments: ["@fos_user.user_manager",{instagram: instagramId},"%instagram.client.id%","%instagram.client.secret%","@logger", "@user_service"]
        tags:
            - { name: monolog.logger }
            
            
    social_profile_util:
        class: "%social_profile_util.class%"
        arguments: ["@user_service","@logger"]
      
      
